Repository fusebit/marketplace, pull requests merged in 2022-04, with the labels that each got.

#12 Update readme wording
  README.md
  src/react-marketplace/README.md
Labels: semver:none

#13 ENG 1452 Marketplace tile UI updates
  src/react-marketplace/components/Button/Button.module.css
  src/react-marketplace/components/Card/Card.module.css
  src/react-marketplace/components/Description/Description.module.css
  src/react-marketplace/components/Description/Description.tsx
  src/react-marketplace/components/Description/index.ts
  src/react-marketplace/components/Image/Image.module.css
  src/react-marketplace/components/Link/Link.module.css
  src/react-marketplace/components/Marketplace/Marketplace.tsx
  src/react-marketplace/components/Subtitle/Subtitle.module.css
  src/react-marketplace/components/Subtitle/Subtitle.tsx
  src/react-marketplace/components/Subtitle/index.ts
  src/react-marketplace/components/Tile/Tile.module.css
  src/react-marketplace/components/Tile/Tile.tsx
  src/react-marketplace/components/Title/Title.module.css
  src/react-marketplace/components/hooks/useTile.tsx
  src/react-marketplace/components/interfaces/marketplace.ts
  tsconfig.json
Labels: semver:minor

#14 ENG 1452 Marketplace tile UI updates
  src/react-marketplace/components/Card/Card.module.css
  src/react-marketplace/components/Marketplace/Marketplace.tsx
  src/react-marketplace/components/Spinner/Spinner.module.css
  src/react-marketplace/components/Spinner/Spinner.tsx
  src/react-marketplace/components/Tile/Tile.tsx
Labels: semver:patch
